{% set name = "tbats" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tbats-{{ version }}.tar.gz
  sha256: 5a703f4ffcc99e3f7c6e62338ce86489f0f9713bfab3409efeeaa7557f98201c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - numpy
    - pmdarima
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - tbats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intive-DataScience/tbats
  summary: BATS and TBATS for time series forecasting
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hrzn
    - tomasvanpottelbergh
    - gnwhr
